export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const BOOK_ADD_SUCCESS = 'BOOK_ADD_SUCCESS'
export const BOOK_ADD_FAIL = 'BOOK_ADD_FAIL'

export const BOOK_FOR_SALE_GET = 'BOOK_FOR_SALE_GET'

export const BOOK_DELETE_SUCCESS = 'BOOK_DELETE_SUCCESS'

/**************** User Types **********************/
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAILURE = 'USER_REGISTER_FAILURE'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE'
