export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

/**************** User Types **********************/
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'


/**************** Book Types **********************/
export const BOOK_MY_BOOKS_SUCCESS = 'BOOK_MY_BOOKS_SUCCESS'
export const BOOK_MY_BOOKS_FAILURE = 'BOOK_MY_BOOKS_FAILURE'

export const BOOK_GUEST_SEARCH_SUCCESS = 'BOOK_GUEST_SEARCH_SUCCESS'
export const BOOK_GUEST_SEARCH_FAILURE = 'BOOK_GUEST_SEARCH_FAILURE'

export const BOOK_VIEW_ONE_SUCCESS = 'BOOK_VIEW_ONE_SUCCESS'
export const BOOK_VIEW_ONE_FAILURE = 'BOOK_VIEW_ONE_FAILURE'

export const BOOK_REQUEST_SUCCESS = 'BOOK_REQUEST_SUCCESS'
export const BOOK_REQUEST_FAILURE = 'BOOK_REQUEST_FAILURE'

export const BOOK_ADD_NEW_SUCCESS = 'BOOK_ADD_NEW_SUCCESS'
export const BOOK_ADD_NEW_FAILURE = 'BOOK_ADD_NEW_FAILURE'

export const BOOK_DELETE_SUCCESS = 'BOOK_DELETE_SUCCESS'
export const BOOK_DELETE_FAILURE = 'BOOK_DELETE_FAILURE'


/**************** Order Types **********************/
export const ORDER_ADD_NEW_SUCCESS = 'ORDER_ADD_NEW_SUCCESS'
export const ORDER_ADD_NEW_FAILURE = 'ORDER_ADD_NEW_FAILURE'

export const ORDER_MY_ORDERS_SUCCESS = 'ORDER_MY_ORDERS_SUCCESS'
export const ORDER_MY_ORDERS_FAILURE = 'ORDER_MY_ORDERS_FAILURE'